import assert from 'node:assert/strict';
import {getSchema} from '@tiptap/core';
import StarterKit from '@tiptap/starter-kit';
import {EditorState,TextSelection} from '@tiptap/pm/state';
import {incomingDocument} from '../lib/editor-sync';
const schema=getSchema([StarterKit.configure({italic:false})]);
const body={type:'doc',content:[{type:'paragraph',content:[{type:'text',text:'first line'}]},{type:'paragraph',content:[{type:'text',text:'last line'}]}]};
const doc=schema.nodeFromJSON(body);
const state=EditorState.create({schema,doc,selection:TextSelection.create(doc,3,5)});
const reordered=JSON.parse(JSON.stringify(body),(_k,v)=>v && !Array.isArray(v) && typeof v==='object'?Object.fromEntries(Object.entries(v).reverse()):v);
assert.notEqual(JSON.stringify(body),JSON.stringify(reordered));
assert.equal(incomingDocument(state,reordered),null);
assert.ok(state.tr.replaceWith(0,doc.content.size,doc.content).selection.from>10);
const changed=structuredClone(body);changed.content[1].content[0].text='remote update';
const tr=incomingDocument(state,changed)!;
assert.equal(tr.selection.from,3);assert.equal(tr.selection.to,5);
assert.equal(tr.getMeta('addToHistory'),false);
const short=incomingDocument(state,{type:'doc',content:[{type:'paragraph'}]})!;
assert.ok(short.selection.from<=short.doc.content.size);
console.log('PASS editor sync: old jump reproduced, reordered JSON ignored, remote selection preserved');
