import assert from 'node:assert/strict';
import {Editor} from '@tiptap/core';
import StarterKit from '@tiptap/starter-kit';
import {TextStyle,Color,BackgroundColor,FontSize} from '@tiptap/extension-text-style';
import {LineBand} from '../lib/line-band';
import {memoView} from '../lib/mobile-navigation';
const editor=new Editor({element:null,extensions:[StarterKit.configure({italic:false}),TextStyle,Color,BackgroundColor,FontSize,LineBand],content:{type:'doc',content:[{type:'paragraph',content:[{type:'text',text:'first'}]},{type:'paragraph',content:[{type:'text',text:'second'}]},{type:'paragraph'}]}});
editor.commands.setTextSelection(3);
editor.commands.setLineBand('#31465c');
assert.equal(editor.getJSON().content![0].attrs?.bandColor,'#31465c');
assert.equal(editor.getJSON().content![1].attrs?.bandColor,null);
editor.commands.setTextSelection({from:2,to:10});
editor.commands.setLineBand('#493c59');
assert.equal(editor.getJSON().content![0].attrs?.bandColor,'#493c59');
assert.equal(editor.getJSON().content![1].attrs?.bandColor,'#493c59');
editor.commands.setTextSelection(6);
assert.equal(editor.commands.splitBandParagraph(),true);
assert.equal(editor.getJSON().content![0].attrs?.bandColor,'#493c59');
assert.equal(editor.getJSON().content![1].attrs?.bandColor,null);
editor.commands.setLineBand('#334c3e');
assert.equal(editor.getJSON().content![1].attrs?.bandColor,'#334c3e');
editor.commands.insertContent({type:'text',text:'空行に入力'});
assert.equal(editor.getJSON().content![1].attrs?.bandColor,'#334c3e');
editor.commands.setLineBand(null);
assert.equal(editor.getJSON().content![1].attrs?.bandColor,null);
// Selecting up to the next paragraph's start must not color that paragraph.
editor.commands.setTextSelection({from:2,to:8});
editor.commands.setLineBand('#57383c');
assert.equal(editor.getJSON().content![1].attrs?.bandColor,null);
const roundtrip=editor.schema.nodeFromJSON(JSON.parse(JSON.stringify(editor.getJSON())));
assert.ok(roundtrip.eq(editor.state.doc));
editor.commands.setTextSelection(3);editor.commands.splitBandParagraph();
assert.equal(editor.getJSON().content![1].attrs?.bandColor,null);
const id='00000000-0000-4000-8000-000000000001';
assert.deepEqual(memoView(null,'#note='+id),{kind:'note',id});
assert.equal(memoView(null,''),null);
assert.deepEqual(memoView({syncMemoView:'list'},''),{kind:'list'});
assert.deepEqual(memoView(null,'#notes'),{kind:'list'});
console.log('PASS bands: cursor, partial/multiline selection, empty paragraph, Enter/end/middle, clear, serialization; navigation states');
editor.destroy();
